# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    date:
        label: opiy.smallcontactform::lang.controller.filter.columns.date
        type: daterange
        conditions: date >= ':after' AND date <= ':before'
